### PR TITLE
Integrate versionbot

### PR DESCRIPTION
**Pull request by josephroberts**
Change-type: patch
Signed-off-by: Joseph Roberts <joe@resin.io>

Connects with #53

### CODE REVIEW

**Comment by josephroberts** [comment]
@majorz this PR will enable versionbot on the repo - please read https://github.com/resin-io/process/blob/master/process/Commit_and_PR_Guidelines.md for more info. 

The most important things are that you start using `git commit --signoff`, add a change type to the commit (see the commit on this PR for an example) and use the `procbots/versionbot/ready-to-merge` label to merge

**Comment by lurch** [comment]
Didn't we decide that rather than including a versionbot conf file inside each repo, we'd just let versionbot default to its own internal config?

**Comment by hedss** [comment]
@lurch This isn't an NPM packaged repo, and `versionist` still isn't able to work (or preferably fail with warning) on repos that don't have one.

**Comment by josephroberts** [comment]
Turns out there is some outstanding issues with getting VB running on repos under the `resin-io-modules` org so I am going to leave this open for now.

**Pull request merged**
