### PR TITLE
Improved Travis CI config

### PR DESCRIPTION
**Pull request by majorz**
In addition to making the builds quicker by not forcing new rustfmt install on each build I cleaned up the file a bit and made clippy warnings to be treated as errors. In a consecutive PR we can make the nightly builds to disallow failures, which not allow propagation of PRs introducing clippy warnings (now errors).

Connects-To: #66

### CODE REVIEW

**Comment by josephroberts** [comment]
@majorz needs a version bump

**Comment by majorz** [comment]
I bumped it up with rewriting the latest commit message, but it looks like Travis has stuck now. I will force a rebuild.

**Comment by josephroberts** [comment]
@majorz what about the version in `cargo.toml`?

**Comment by majorz** [comment]
> @majorz what about the version in `cargo.toml`?

Right, for some reason I deleted the version update before committing... One more reason to make versionist cargo aware sooner :)

**Pull request merged**
